In [1]:
import pandas as pd
import numpy as np

In [2]:
x = np.array(([2, 9], [1, 5], [3, 4]), dtype = float)
y = np.array(([92], [86], [89]), dtype = float)
x = x / np.amax(x, axis = 0)
y = y / 100

In [3]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [4]:
def derivatives_sigmoid(x):
    return x * (1 - x)

In [5]:
epoch = 5
lr = 0.5

ip_neurons = 2
hp_neurons = 3
op_neurons = 1

wh = np.random.uniform(size = (ip_neurons, hp_neurons))
wout = np.random.uniform(size = (hp_neurons, op_neurons))

In [11]:
for i in range(epoch):
    hlayer_sum = np.dot(x, wh)
    hlayer_act = sigmoid(hlayer_sum)
    op_sum = np.dot(hlayer_act, wout)
    op_act = sigmoid(op_sum)
    
    EO = y - op_act
    outgrad = derivatives_sigmoid(op_act)
    d_op = EO * outgrad
    EH = d_op.dot(wout.T)
    hiddengrad = derivatives_sigmoid(hlayer_act)
    d_hiddenlayer = EH * hiddengrad
    
    wout += hlayer_act.T.dot(d_op) * lr
    wh += x.T.dot(d_hiddenlayer) * lr
    
    print(f"_________________EPOCH - {i + 1} Starts_______________")
    print(f"Input:\n{str(x)}")
    print(f"Actual Output:\n{str(y)}")
    print(f"Predicted output:\n{op_act}")
    print(f"_________________EPOCH - {i + 1} Ends_________________\n")
    
print(f"Input:\n{str(x)}")
print(f"Actual output:\n{str(y)}")
print(f"Predicted output:\n{op_act}")

_________________EPOCH - 1 Starts_______________
Input:
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.44444444]]
Actual Output:
[[0.92]
 [0.86]
 [0.89]]
Predicted output:
[[0.87139833]
 [0.84004229]
 [0.85483511]]
_________________EPOCH - 1 Ends_________________

_________________EPOCH - 2 Starts_______________
Input:
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.44444444]]
Actual Output:
[[0.92]
 [0.86]
 [0.89]]
Predicted output:
[[0.87251612]
 [0.84118799]
 [0.85599942]]
_________________EPOCH - 2 Ends_________________

_________________EPOCH - 3 Starts_______________
Input:
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.44444444]]
Actual Output:
[[0.92]
 [0.86]
 [0.89]]
Predicted output:
[[0.87358284]
 [0.84228286]
 [0.85711141]]
_________________EPOCH - 3 Ends_________________

_________________EPOCH - 4 Starts_______________
Input:
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.44444444]]
Actual Output:
[[0.